version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    rebase-strategy: "auto"
    groups:
      semver_updates:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"

