engines:
  rubocop:
    enabled: true
    channel: rubocop-0-49
  bundler-audit:
    enabled: true
  flog:
    enabled: true
  flay:
    enabled: true
  eslint:
    enabled: true
    config:
      config: .eslintrc
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
    exclude_paths:
      - 'app/controllers/stories_controller.rb'
      - 'app/controllers/teams_controller.rb'
      - 'app/controllers/projects_controller.rb'
      - 'app/api/v1/projects.rb'
      - 'app/api/v1/teams.rb'
      - 'app/operations/story_operations/state_change_notification.rb'
      - 'app/admin/*.rb'
exclude_paths:
  - "Gemfile.lock"
  - "db/schema.rb"
  - "db/migrate/*.rb"
  - "spec/"
  - "fixtures/"
  - "doc/"
  - "vendor/"
  - "public/javascripts"
