engines:
  rubocop:
    enabled: true
  bundler-audit:
    enabled: true
  flog:
    enabled: true
  flay:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
exclude_paths:
  - "Gemfile.lock"
  - "db/schema.rb"
  - "db/migrate/*.rb"
  - "spec/"
  - "fixtures/"
  - "doc/"
  - "vendor/"
