AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'Gemfile'

Rails:
  Enabled: true

Rails/TimeZone:
  Enabled: false

Rails/Date:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Documentation:
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/RedundantReturn:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/ClosingParenthesisIndentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  CountComments: false
  Max: 25

Metrics/AbcSize:
  Enabled: true
  Max: 25
  Exclude:
    - 'app/controllers/stories_controller.rb'
    - 'app/controllers/projects_controller.rb'
    - 'app/presenters/activity_presenter.rb'

Metrics/ClassLength:
  Enabled: true
  Max: 110
  Exclude:
   - 'app/controllers/projects_controller.rb'

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 8

Metrics/CyclomaticComplexity:
  Enabled: true
  Exclude:
    - 'spec/support/integration_helpers.rb'

Metrics/BlockLength:
  Enabled: false
