AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'Gemfile'

Rails:
  Enabled: true

Rails/TimeZone:
  Enabled: false

Rails/Date:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Documentation:
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/RedundantReturn:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/ClosingParenthesisIndentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  CountComments: false
  Max: 25

Metrics/AbcSize:
  Enabled: true
  Exclude:
    - 'app/operations/story_operations/state_change_notification.rb'
    - 'app/serializers/project_serializer.rb'
    - 'app/controllers/users_controller.rb'
    - 'app/controllers/stories_controller.rb'
    - 'app/controllers/tag_groups_controller.rb'
    - 'app/controllers/changesets_controller.rb'
    - 'app/controllers/teams_controller.rb'
    - 'app/controllers/integrations_controller.rb'
    - 'app/controllers/projects_controller.rb'
    - 'app/controllers/registrations_controller.rb'
    - 'app/controllers/confirmations_controller.rb'
    - 'app/workers/import_worker.rb'
    - 'app/presenters/activity_presenter.rb'
    - 'lib/tasks/i18n_missing_keys.rake'

Metrics/ClassLength:
  Enabled: true
  Max: 105
  Exclude:
   - 'app/controllers/projects_controller.rb'

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
