AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'Gemfile'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  CountComments: false
  Max: 25

Metrics/AbcSize:
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true

Documentation:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false
