name: ci
on:
  pull_request_target:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref
        default: master
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-20.04-16core
    env:
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
    steps:
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          sudo mysql -uroot -proot -e"ALTER USER 'root'@'localhost' IDENTIFIED WITH caching_sha2_password BY '';"
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.git-ref }}
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup
        run: bin/setup
      - name: Run tests
        run: bin/ci

  autodeploy-dependabot-prs:
    needs: test
    runs-on: ubuntu-20.04
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Merge Dependabot PR
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
          config: |
            Host *
              StrictHostKeyChecking no
              UserKnownHostsFile=/dev/null
      - name: deploy
        run: bundle exec bard deploy --skip-ci

